- name: Install and Start Nginx
  hosts: all
  become: true

  tasks:
   - name: Install the Ngnix
     apt:
      name: nginx
      state: present

   - name: Start the Nginx
     shell: systemctl start nginx       
